[package]
name = "wx"
version = "0.1.0"
authors = ["colder <colder@vitarn.com>"]
edition = "2018"
license = "MIT"
keywords = ["wx", "weixin", "wechat"]
description = "wx sdk all-in-one"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
